name: Generate Podcast Feeds
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pyyaml

      - name: Run Feed Generator
        run: python feed.py

      - name: Check for file changes
        id: changes_check
        run: |
          if git diff --quiet; then
            echo "No changes to commit."
            echo "changes=false" >> $GITHUB_ENV
          else
            echo "Changes found, proceeding with commit."
            echo "changes=true" >> $GITHUB_ENV
          fi

      - name: Commit changes and Push repo
        if: env.changes == 'true'
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"
          git add .
          git commit -m "Modified Feed - Automated commit from GitHub Actions"
          git push
