name: Generate Podcast Feeds
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4.2.1
      - name: Setup Python
        uses: actions/setup-python@v5.2.0
        with:
          python-version: '3.10'
      - name: Install Dependecies
        run: |
          python -m pip install --upgrade pip
          pip install pyyaml
      - name: Run Feed Generador
        run: python feed.py
      - name: Push Repo
        run: |
          git config user.name @DouglasAmarelo_Github-actions
          git config user.email DouglasAmarelo_Github-actions@github.com
          git add .
          git commit -m "Modified Feed"
          git push
